### ISSUE TITLE
Windowing - TitleBar sample - Titlebar always null

### ISSUE THREAD

**Issue by tinmac** [microsoft/WindowsAppSDK-Samples#116]
If we navigate to the 'Titlebar' page, pressing any of the three buttons results in a null ref exception:

![image](https://user-images.githubusercontent.com/6616946/139305995-83285f72-1d72-425e-9576-b87e871cd3a5.png)

Code is unaltered & run from fresh clone of this repo.

WinUI project.

I note you refer to this as being fixed in [#71](https://github.com/microsoft/WindowsAppSDK-Samples/pull/71#issue-985857581) and [#94](https://github.com/microsoft/WindowsAppSDK-Samples/issues/94#issue-1014953264) but it doesnt seem to be @samanthamsong, can you provide any guidance?

**Comment by MahmudOnWeb** [comment]
I can confirm I am experiencing this too. I get the window handle, then I get the Window id and get the AppWindow from window Id. AppWindow is there and working fine, but it's TitleBar is always null.

**Comment by mevey** [comment]
AppWindow titlebar APIs, including ResetToDefault , work only on Windows 11 builds. There's an error in the sample which I will correct. AppWindowTitleBar. IsCustomizationSupported has to return true for me to call ResetToDefault successfully.  Titlebar object is null on Windows 10 and earlier versions. We are working to bring this functionality downlevel in upcoming releases. I'll update the sample accordingly.

**Comment by bpulliam** [comment]
The sample has been updated to use WindowsAppSDK 1.2.
Also, the AppWindow APIs have been ported to downlevel.
 If you still see this issue, reactivate with your updated results.
