### ISSUE TITLE
Update Templates To Use Preview 3

### ISSUE THREAD

**Issue by AgneLukoseviciute** [microsoft/WindowsAppSDK-Samples#121]
https://github.com/microsoft/WindowsAppSDK-Samples/blob/fbcbdeb7e9c23c093d79cfb810512d494343174d/Templates/VSIX/Directory.Build.props#L8

I believe this should reference `1.0.0-preview3` instead, no?

**Comment by angelazhangmsft** [comment]
We plan to update all the samples/templates to 1.0.0 (GA) next week.

**Comment by angelazhangmsft** [comment]
The templates have been updated to 1.0.0 and are available for download [here](https://github.com/microsoft/WindowsAppSDK-Samples/releases/tag/GA1.0SampleTemplateVSIX)!
