### ISSUE TITLE
Dynamic Dependencies sample does not build correctly

### ISSUE THREAD

**Issue by erik0686** [microsoft/WindowsAppSDK-Samples#143]
The following sample:
https://github.com/microsoft/WindowsAppSDK-Samples/tree/main/Samples/DynamicDependencies/DirectX

shoes the following error when building:
1>C:\WindowsAppSDK-Samples\Samples\DynamicDependencies\DirectX\D3D9ExSample.cpp(13,10): fatal error C1083: Cannot open include file: 'd3dx9.h': No such file or directory
1>C:\WindowsAppSDK-Samples\Samples\DynamicDependencies\DirectX\BackgroundThread.cpp(12,10): fatal error C1083: Cannot open include file: 'd3dx9.h': No such file or directory

Might there be an issue with the sample?

**Comment by angelazhangmsft** [comment]
The DirectX sample requires downloading the DirectX SDK and Framework Package (it has extra dependencies): https://github.com/microsoft/WindowsAppSDK-Samples/tree/main/Samples/DynamicDependencies

**Comment by btueffers** [comment]
@erik0686 I'm closing this issue under the assumption that downloading DirectX SDK and Framework Package was the fix!
