### ISSUE TITLE
Unable to run CsWpfInstancing

### ISSUE THREAD

**Issue by aqibbanday** [microsoft/WindowsAppSDK-Samples#151]
I am unable to run CsWpfInstancing

**Comment by aqibbanday** [comment]
Hi, i run the project but the nothing launches and the debugger stops.

**Comment by angelazhangmsft** [comment]
I see. To confirm, did you run the latest installer (WindowsAppRuntimeInstall.exe) for deploying unpackaged apps? https://docs.microsoft.com/windows/apps/windows-app-sdk/deploy-unpackaged-apps

**Comment by aqibbanday** [comment]
> I see. To confirm, did you run the latest installer (WindowsAppRuntimeInstall.exe) for deploying unpackaged apps? https://docs.microsoft.com/windows/apps/windows-app-sdk/deploy-unpackaged-apps

ok, that resolved the issue.
