### ISSUE TITLE
 DeploymentManager CSharp Sample Getting COM Execeptions

### ISSUE THREAD

**Issue by mjfusa** [microsoft/WindowsAppSDK-Samples#154]
I'm getting the following errors with the DeploymentManager sample: 
Are these APIs, working properly, or is there an issue with the sample?

Scenario 1: GetStatus:
Result Status: PackagelnstallRequired
Result ExtendedError. System.Runtime.lnteropServices.COMException (Ox80070490): Element not found. (Ox80070490)

Scenario 2: Initialize:
Result Status: PackagelnstallFailed
Result ExtendedError. System.Runtime.lnteropServices.COMException (Ox800700E8): The pipe is being closed. (Ox800700E8)
Initialize() failed to ensure the WindowsAppRuntime.

@dkbennett @angelazhangmsft

**Comment by bpulliam** [comment]
The sample has been updated to use WindowsAppSDK 1.2. If you still see this issue, reactivate with your updated results.
