### ISSUE TITLE
DirectWriteCore.dll not found

### ISSUE THREAD

**Issue by sergeyn** [microsoft/WindowsAppSDK-Samples#164]
I cannot run text rendering sample, it complains about DirectWriteCore.dll not found when I try to run it after building.

**Comment by btueffers** [comment]
Hi @sergeyn, can you provide more information about the problem you're encountering? Is there a specific message? Do you see the Microsoft.WindowsAppSDK package installed in the project?

**Comment by sergeyn** [comment]
Hi @btueffers ,

I'm trying to build/run unpackaged project "DWriteCoreGallery"  under debugger to see how it works.  There's no reference to windowsappsdk. There's one in (packaging) project , but that one I cannot debug.

**Comment by duncanmacmichael** [comment]
Hi @sergeyn, sorry for the delay on this. I just attempted to reproduce your issue but wasn't able to - on my machine, I was able to successfully build and run the DWriteCoreGallery sample. To do so, I followed the instructions on [this](https://docs.microsoft.com/en-us/windows/apps/windows-app-sdk/set-up-your-development-environment?tabs=vs-2022-17-1-a%2Cvs-2022-17-1-b) page and made sure to install the correct workloads and components for Visual Studio 2022, and additionally installed the Win11 SDK from the optional VS components list. I also made sure to set the DWriteCoreGallery (packaging) project as the startup project. I could then run the sample app, set breakpoints, etc. 

You might have already done all this but can you confirm if you have tried all these steps first? Thanks!

**Comment by bpulliam** [comment]
The sample has been updated to use WindowsAppSDK 1.2. If you still see this issue, reactivate with your updated results.
