### ISSUE TITLE
Unable to compile Mica-WebView2

### ISSUE THREAD

**Issue by suneetsasidharan** [microsoft/WindowsAppSDK-Samples#236]
Unable to compile a clean import of Mica-WebView2 solution.

Error	MSB3231	Unable to remove directory "x64\Debug\". The process cannot access the file 'MicaWebView2.log' because it is being used by another process.	Mica-WebView2	F:\microsoft WindowsAppSDK-Samples main Samples-Mica\cpp-WebView2\Mica-WebView2\MicaWebView2.vcxproj	209

**Comment by bpulliam** [comment]
That message can result from a background msbuild process.  If you still have trouble building that sample, please share a full binlog.  Thanks!
