### ISSUE TITLE
Bindings not found

### ISSUE THREAD

**Issue by acrigney** [microsoft/WindowsAppSDK-Samples#262]
First build of the application gives.
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS1061	'MainPage' does not contain a definition for 'Bindings' and no accessible extension method 'Bindings' accepting a first argument of type 'MainPage' could be found (are you missing a using directive or an assembly reference?)	PhotoEditor	C:\Projects\WindowsAppSDK-Samples-main\WindowsAppSDK-Samples-main\Samples\PhotoEditor\cs-winui\obj\x64\Debug\net6.0-windows10.0.19041.0\win10-x64\MainPage.g.cs	1066	Active

**Comment by bpulliam** [comment]
We've just updated our dependencies and references to WindowsAppSDK 1.2 preview in preparation for the 1.2 stable release.  Can you confirm that the issue still exists on a current tree?  If so, please include a binlog and we'll take a look.

**Comment by bpulliam** [comment]
If you are still seeing this on 1.4, please let us know.
