### ISSUE TITLE
WinForms/WPF Packaged Sample for MRTCore 

### ISSUE THREAD

**Issue by nickrandolph** [microsoft/WindowsAppSDK-Samples#31]
Would it be possible to include an sample that shows how to use MRTCore within a WinForms and/or WPF application. Eventually this would show both packaged and unpackaged applications but for the timebeing showing how to use MRTCore in a packaged application would be great.

**Comment by kevinguo305** [comment]
Thank you for the feedback Nick! We currently have someone from the dev team expanding the samples to showcase that scenario

**Comment by nickrandolph** [comment]
If they need someone to test the samples out and provide feedback - always happy to help. Thanks @kevinguo305

**Comment by kevinguo305** [comment]
Hi Nick,

We've made sure MRTCore samples have both an unpackaged WinForms as well as a packaged WPF application. We hope this is helpful! Please reopen issue if you think this GitHub issue hasn't addressed.
