### ISSUE TITLE
Update samples to reference Reunion 0.8

### ISSUE THREAD

**Issue by angelazhangmsft** [microsoft/WindowsAppSDK-Samples#46]

**Comment by MarkIngramUK** [comment]
The samples can't use Reunion 0.8 because unpackaged support for MRTCore is only available in the preview.

As 1.0 experimental1 is now available, I suggest updating the samples to reference that instead.

**Comment by angelazhangmsft** [comment]
@MarkIngramUK yes since unpackaged support is only available in the preview, we left the MRTCore samples at 0.8-preview. We do plan to update the samples soon to a preview version of 1.0 given the name change from Reunion to Windows App SDK. However in general we only plan to update samples for GA releases of WinAppSDK.
