### ISSUE TITLE
The sample cs-winui SampleApp expects the pubxml file name to be win10-x64.pubxml

### ISSUE THREAD

**Issue by capegreg** [microsoft/WindowsAppSDK-Samples#73]
Publishing fails unless "FolderProfile.pubxml" is renamed to "win10-x64.pubxml"

Actual publish profile name
C:\source\repos\cs-winui\SampleApp\Properties\PublishProfiles\FolderProfile.pubxml

Error on publish
Could not find the publish profile C:\source\repos\cs-winui\SampleApp\Properties\PublishProfiles\win10-x64.pubxml.

**Comment by angelazhangmsft** [comment]
@capegreg I assume you are referring to the Windowing sample here? https://github.com/microsoft/WindowsAppSDK-Samples/tree/main/Samples/Windowing/cs-winui

/cc @samanthamsong

**Comment by capegreg** [comment]
Yes.

**Comment by angelazhangmsft** [comment]
I am also seeing this issue with the other samples (e.g. Resource Management). The problem seems to be that these files are missing: https://github.com/microsoft/WindowsAppSDK/tree/main/dev/VSIX/ProjectTemplates/Desktop/CSharp/PackagedApp/BlankApp/Properties/PublishProfiles
